#Do NOT change the config version. You will break the plugin by doing so....
Version: 1


DEBUG: false
DenyEnderpearl: true
DynmapEnable: true
DynmapHideByDefault: false
DynmapPriority: 0
WhooshEffect: true
PortalRedirection: true
KnockBack: 3.0
TimerTicks: 5
RemountDelayTicks: 0
KillPlayer: false
ShapeRound: false
FillAutosaveFrequency: 30
FillMemoryTolerance: 500
PreventBlockPlace: false
PreventMobSpawn: false